URL_shortener_project/URL_shortener_app/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'URL_shortener_app' # for namespacing
urlpatterns = [
    path('', views.index, name='index'),
    path('visit/', views.visit, name='visit'),
    path('shorten_URL/', views.shorten_URL, name='shorten_URL'),
    path('you_lose_dinosaur/', TemplateView.as_view(template_name="URL_shortener_app/you_lose_dinosaur.html"), name='you_lose_dinosaur'),
    path('<shortcut>/', views.visit_direct, name='visit_direct')
    # path('', views.test, name='index')
]

URL_shortener_project/URL_shortener_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('URL_shortener_app.urls')) # Note: all your app urls will start with this path
]

URL_shortener_project/URL_shortener_app/models.py
from django.db import models
from datetime import datetime

# Create your models here.

#by convention you should use a singluar name for your class because it creates one instance
class Short_Cut(models.Model):
    original_url = models.TextField(unique=True)
    shortcut = models.TextField(unique=True, primary_key=True)
    created_date = models.DateTimeField(default=datetime.now())

    # once you have set up a class you have to run a migrations with python \manage.py makemigrations doDoApp. Once this is successful you should have a 0001_initial in yoru omigrations folder. After any changes to models you must make another migration. this creates instructions for migrating. python manage.py migrate then actually migrates things to the app.

    def __str__(self):
        return self.shortcut

URL_shortener_project/URL_shortener_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from .models import Short_Cut
from django.urls import reverse
import requests, random


def visit(request, original_url):
    print('in visit')
    url = request.POST['original_url']
    return redirect(url)


def visit_direct(request, shortcut):
    go = get_object_or_404(Short_Cut, shortcut=shortcut)
    return redirect(go.original_url)
    # return HttpResponse(go)


def index(request):
    print("you called index")
    context = {'shortcut_list': Short_Cut.objects.all()}
    return render(request, 'URL_shortener_app/index.html', context)


def shorten_URL(request):
    if request.method == 'POST':
        url = request.POST['to_shorten']
        print("URL recieved")
        if not url.startswith('http'):
            url = 'http://' + url
            print("added http to url")
        if Short_Cut.objects.filter(original_url=url).exists():
            print("that url does exist in the database!")
            go = get_object_or_404(Short_Cut, original_url=url)
            # return HttpResponse(f'the new url for {url} is localhost800{go.shortcut}')
            context = {'shortcut': go, 'url': url, 'message': f'Your new url for {url} is: localhost:8000/ + {go}. To access your site directly from your browser, enter "localhost:8000/{go}"" into your search bar.'}
            return render(request, 'URL_shortener_app/index.html', context)
        print("it wasn't in the data base")
        try:
            response = requests.get(url)
            if response.status_code == 200:
                print("that is a good url")
                chars = "abcdefghijklmnopqrstuvwxzyABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
                while True:
                    value = "".join(random.choice(chars) for _ in range(5))
                    if value not in Short_Cut.objects.all():
                        Short_Cut(original_url=url, shortcut=value).save()
                        context = {'shortcut': value, 'url': url, 'message': f'Your new url for {url} is: localhost:8000/ + {value}. To access your site directly from your browser, enter "localhost:8000/{value}"" into your search bar.'}
                        # return HttpResponse(f'the new url for {url} is localhost800{value}')
                        return render(request, 'URL_shortener_app/index.html', context)
            else:
                raise Exception
        except:
            return redirect('URL_shortener_app:you_lose_dinosaur')
            # return HttpResponse("that didn't work! Are you sure your url was correct?")
    else:
        return redirect('URL_shortener_app:index')

URL_shortener_project/URL_shortener_app/templates/URL_shortener_app/index.html
<!DOCTYPE html>
<html>
<head>
  <title>URL shortener</title>
  {% load static %}
  <!-- <link rel="stylesheet" type="text/css" href="{%static 'toDoApp/style.css' %}"/> -->
</head>

<body>
  <div id="app">
    <h1>Enter a url you would like to shorten:</h1>

    <div class="holder">

      <form action="{% url 'URL_shortener_app:shorten_URL'  %}" method="post">
        {% csrf_token%}
        <p>Enter a url to shorten: <input type="text" name="to_shorten"></p>
        <button type="submit">Submit</button>

        <h1> <a href="{{url}}">{{shortcut}}</a></h1>
            <h2> {{message}}</h2>
        <!-- <h2> Your new url for {{url}} is: thisSite + {{shortcut}}. To access your site directly from your browser, enter "thisSite{{shortcut}}"" into your search bar.</h2> -->
        <!-- <p>Shortcut you want:<input type="text" name="shortcut"></p> -->
      </form>

      <!-- <form action="{% url 'URL_shortener_app:index'  %}" method="get">
        <h2>Stored urls:</h2>
        <ul>
          {% for item in shortcut_list %}
          <li>
            <p><a href="{{item.original_url}}">{{ item.shortcut }}</a>: {{item.id}},  {{item.original_url }},   {{ item.created_date }}</p>
          </li>
          {% endfor %}
      </form> -->

<!--
      <form action="{% url 'URL_shortener_app:shorten_URL'  %}" method="get">
        <h2>New URL:</h2>
        <ul>
          {% for item in shortcut_list %}
          <li>
            <p><a href="{{item.original_url}}">{{ item.shortcut }}</a>: {{item.id}},  {{item.original_url }},   {{ item.created_date }}</p>
          </li>
          {% endfor %}
      </form> -->



      </ul>
    </div>
  </div>
</body>
<html>

URL_shortener_project/URL_shortener_app/templates/URL_shortener_app/you_lose_dinosaur.html
<!DOCTYPE html>
<html>
<head>
  <title>URL shortener</title>
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'URL_shortener_app/style.css' %}"/>
</head>

<body>
<h1>That didn't work!  Are you sure your url was correct???!!?! </h1>
<div id="dino">
</div>
</body>
<html>